apiVersion: skaffold/v3
kind: Config
deploy: {}
manifests:
  rawYaml:
    - "./infra/k8s/*"
build:
  local:
    push: false
  artifacts:
    - image: rtpa25/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: . #thrown into the container
    - image: rtpa25/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - "**/*.ts"
          - "**/*.tsx"
          - "**/*.css"
